### PR TITLE
Separate write acknowledge and write strobe generation

### LINKED ISSUE #48: Consecutive single cycle write access
A register map generated by cheby translates each request from the bus interface (APB, Wishbone, ...) to a request on an internal bus (`ibus`). Such a request on the internal bus takes only one cycle ("pulse") independently of when it is executed. While the request on the bus interface might be still active (until it is confirmed/responded to), the internal request vanishes after that one cycle. A write request on the internal bus consists of `wr_req`, `wr_adr`, `wr_dat`, and `wr_sel`. Similarly, a read request consists of `rd_req`, `rd_adr`, and `rd_dat`.
Following the request, the internal bus returns the response. Again, the response is only active during one cycle. It consists of `wr_ack`, and `wr_err` for a write request and of `rd_ack`, `rd_dat`, and `rd_err` for a read request.

Without pipelining, a request is executed immediately, i.e., the data will be written to the register upon the next rising clock edge, while the read data is returned immediately such that the response can be sampled upon the next rising clock edge as well. Using the `pipeline` attribute, the request, the response or both can be sampled before being acted upon/being returned.

Looking at the `bus`, one would expect the following when setting `pipeline: none`:
ibus_theo

Unfortunately, this is not true and it seems as if the write acknowledge signal, `wr_ack`, is first sampled and only returned one cycle later (even with `pipeline: none`):
ibus_now

Why is this a problem?

It seems more consistent to me that the write and read "response" behave the same, i.e. they are "instantaneous" while purely combinatorial paths can be avoided by using the appropriate `pipeline` settings. Right now, setting `pipeline` to `wr-in` or `wr-out` further increases the latency.
But more importantly, the current setup makes it impossible to have a bus interface with consecutive single cycle write requests. Since the multiplexer returning the `wr_ack` signal is combinatorially based on `wr_adr`, `wr_adr` has to remain constant for at least two cycles: One cycle for the correct routing of the request (`wr_req`/`wr_adr`/`wr_dat`/`wr_sel`) and a second cycle for the always sampled `wr_ack` response. If not, the `wr_ack` coming in the second cycle is not forwarded (and hence, lost) as the address of the next request might have changed the multiplexer.

The following lines from [`proto/cheby/hdl/genreg.py`](https://github.com/tgingold-cern/cheby/blob/5073b7f62bb5ee3a8c16d481df52ed8ffcfaf000/proto/cheby/hdl/genreg.py#L605) are at the heart of the problem: Instead of creating a combinatorial path between the request, `n.h_wreq`, and the response, `n.h_wack`, the signal is sampled.

```python
    def gen_processes(self, ibus):
        ...
        if n.access in ['rw', 'wo']:
            ...
            if n.h_has_regs:
                ...
                # In case of regs, the strobe is delayed so that it appears at the same time as
                # the value.
                ffproc.sync_stmts.append(HDLAssign(n.h_wack, n.h_wreq))
                ffproc.rst_stmts.append(HDLAssign(n.h_wack, self.strobe_init()))
```

In contrast, the read acknowledge generation inside the same file is combinatorial:

```python
    def gen_read(self, s, off, ibus, rdproc):
        ...
        # Acknowledge
        if n.h_rack_port is not None:
            rack = n.h_rack_port
            rack = self.strobe_index(off, rack)
        elif ibus.rd_req_del:
            rack = ibus.rd_req_del
        else:
            rack = ibus.rd_req
        s.append(HDLAssign(ibus.rd_ack, rack))
```

I see two possible solutions:
- Adapt `wr_ack` including all bus interfaces such that the interfaces' behavior remains unchanged.
- Separate the multiplexing of the request and the response (might be a good idea anyway), such that the address can be sampled for the multiplexing of the response.

Changing the behavior of `wr_ack` might lead to unwanted side effects. Hence this issue, to further discuss possible solutions on who to realize consecutive single cycle write requests.

Overall, I am wondering if I understood the current implementation correctly and if the delay of the `wr_ack` signal is intended and if yes, for what reasons (the comment mentions something about the strobe)?

### PR DESCRIPTION
**Pull request by lorenzschmid**
The write acknowledge signal is now combinatorically linked to the write request signal. The write strobe signal (that should become active only after the register is updated) is delayed by one cycle as previously.

This allows for consecutive single cycle writes as mentioned in #48.

Since this pull request changes the write acknowledge signal to be asserted one cycle earlier, existing memory maps might execute their write requests one cycle faster now. If the default `pipeline` setting (`wr-in,rd-out`) was used, while being faster the interfaces should still behave correctly. Required testbench changes are visible in 071dbb76732884255e10a04013a5fd088a3a27cf and affect only register write verification's happening now slightly too early (just around the rising edge where previously, the write request took one cycle longer and so the verification was also happening only one cycle later).

Closes #48.

### CODE REVIEW

**Comment by lorenzschmid** [comment]
@tgingold-cern to add to the following point:

> If the default `pipeline` setting (`wr-in,rd-out`) was used, while being faster the interfaces should still behave correctly.

Any write request relaying on the write acknowledge signal is now one cycle faster. About APB, we previously used `pipeline: rd-out` to have the standard conform two cycles write requests. With the changes presented here, the write request takes only one cycle, and we switched to `pipeline: wr-in,rd-out` to restore the old behavior taking two cycles.

**Comment by tgingold-cern** [comment]
Thanks!

**Comment by tgingold-cern** [comment]
Probably you should add a line in README.MD to mention this change.

**Comment by lorenzschmid** [comment]
> Probably you should add a line in README.MD to mention this change.

Done in https://github.com/tgingold-cern/cheby/pull/51.

**Pull request merged**
